[tox]
envlist = pre-commit, pytest

[testenv:pre-commit]
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure

[testenv:pytest]
base_python = python3.12
deps = -r requirements-dev.txt
commands = pytest tests
