"""Add template_name to polls table

Revision ID: a0ee4a685123
Revises: baf69a97f489
Create Date: 2024-02-13 00:19:37.460281

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'a0ee4a685123'
down_revision: Union[str, None] = 'baf69a97f489'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'polls',
        sa.Column('message_id', sa.Integer(), nullable=False),
        sa.Column('chat_id', sa.Integer(), nullable=False),
        sa.Column('message_thread_id', sa.Integer(), nullable=True),
        sa.Column('owner_id', sa.Integer(), nullable=False),
        sa.Column('template_name', sa.String(), nullable=False),
        sa.Column('config', sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ['owner_id'], ['users.id'], name=op.f('fk_polls_owner_id_users')
        ),
        sa.PrimaryKeyConstraint('message_id', name=op.f('pk_polls')),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polls')
    # ### end Alembic commands ###
