"""Delete polls table

Revision ID: baf69a97f489
Revises: 7fc1f37605d7
Create Date: 2024-02-13 00:18:59.965655

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'baf69a97f489'
down_revision: Union[str, None] = '7fc1f37605d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polls')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'polls',
        sa.Column('chat_id', sa.INTEGER(), nullable=False),
        sa.Column('message_thread_id', sa.INTEGER(), nullable=True),
        sa.Column('owner_id', sa.INTEGER(), nullable=False),
        sa.Column('config', sa.VARCHAR(), nullable=False),
        sa.Column('message_id', sa.INTEGER(), nullable=False),
        sa.ForeignKeyConstraint(
            ['owner_id'], ['users.id'], name='fk_polls_owner_id_users'
        ),
    )
    # ### end Alembic commands ###
