"""Delete choices table

Revision ID: ce7c03e87450
Revises: fb7ccad21eb5
Create Date: 2024-02-06 22:30:30.926971

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ce7c03e87450'
down_revision: Union[str, None] = 'fb7ccad21eb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('choices')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'choices',
        sa.Column('message_id', sa.INTEGER(), nullable=False),
        sa.Column('chat_id', sa.INTEGER(), nullable=False),
        sa.Column('message_thread_id', sa.INTEGER(), nullable=True),
        sa.Column('user_id', sa.INTEGER(), nullable=False),
        sa.Column('first_name', sa.VARCHAR(), nullable=False),
        sa.Column('last_name', sa.VARCHAR(), nullable=True),
        sa.Column('username', sa.VARCHAR(), nullable=True),
        sa.Column('choice', sa.VARCHAR(), nullable=False),
        sa.PrimaryKeyConstraint('message_id', name='pk_choices'),
    )
    # ### end Alembic commands ###
