"""Delete polls.config

Revision ID: d36e447d2185
Revises: a0ee4a685123
Create Date: 2024-02-13 00:22:24.219175

"""
from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'd36e447d2185'
down_revision: Union[str, None] = 'a0ee4a685123'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.drop_column('config')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polls', schema=None) as batch_op:
        batch_op.add_column(sa.Column('config', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
